- id: '1567267090938'
  alias: Turn off AC when away
  trigger:
  - entity_id: group.tutti
    platform: state
    from: home
  condition: []
  action:
  - service: script.turn_ac_off
- id: '1567759038729'
  alias: Turn off lights when away
  trigger:
  - entity_id: group.tutti
    platform: state
    from: home
  condition: []
  action:
  - data:
      entity_id: all
    service: light.turn_off
- id: '1568486841268'
  alias: Back up to Dropbox nightly
  trigger:
  - at: 00:00:00
    platform: time
  condition: []
  action:
  - service: hassio.snapshot_full
  - data:
      addon: 7be23ff5_dropbox_sync
      input:
        command: upload
    service: hassio.addon_stdin
- id: '1574456791337'
  alias: Notify Cloe when Alessandro gets home
  trigger:
  - entity_id: person.alessandro_desantis
    event: enter
    platform: zone
    zone: zone.home
  condition: []
  action:
  - data:
      message: Alessandro è arrivato a casa!
    service: notify.notify
- id: '1574456831122'
  alias: Notify Alessandro when Cloe gets home
  trigger:
  - entity_id: person.cloe_filippi
    event: enter
    platform: zone
    zone: zone.home
  condition: []
  action:
  - data:
      message: Cloe è arrivata a casa!
    service: notify.notify
- alias: 'Dim lights at night'
  trigger:
    platform: event
    event_type: state_changed
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ trigger.event.data.entity_id.startswith('light.') }}"
      - condition: template
        value_template: "{{ trigger.event.data.old_state.state != 'on' }}"
      - condition: template
        value_template: "{{ trigger.event.data.new_state.state == 'on' }}"
      - condition: time
        after: '23:00:00'
        before: '05:00:00'
  action:
    service: light.turn_on
    data_template:
      entity_id: "{{ trigger.event.data.entity_id }}"
    data:
      brightness: 100
