- id: '1567267090938'
  alias: 'Summer: Turn off AC when no one''s home'
  trigger:
  - entity_id: group.tutti
    for: 00:30:00
    platform: state
    to: home
  condition: []
  action:
  - data: {}
    service: script.turn_ac_off
- id: '1567267147737'
  alias: 'Summer: Turn on AC when someone''s home'
  trigger:
  - entity_id: group.tutti
    for: 00:30:00
    platform: state
    to: home
  condition:
  - above: '26'
    condition: numeric_state
    entity_id: sensor.esterno_salone_temperature
  action:
  - data: {}
    service: script.turn_ac_on
- id: '1567267391233'
  alias: 'Summer: Turn off AC when it gets cold'
  trigger:
  - below: '24'
    entity_id: sensor.esterno_salone_temperature
    platform: numeric_state
  condition: []
  action:
  - data: {}
    service: script.turn_ac_off
- id: '1567267823406'
  alias: 'Summer: Turn on AC when it gets hot'
  trigger:
  - above: '26'
    entity_id: sensor.esterno_salone_temperature
    platform: numeric_state
  condition:
  - condition: state
    entity_id: group.tutti
    state: home
  action:
  - data: {}
    service: script.turn_ac_on
- id: '1567759038729'
  alias: Turn off all lights when no one's home
  trigger:
  - entity_id: group.tutti
    platform: state
    to: not_home
  condition: []
  action:
  - data:
      entity_id: all
    service: light.turn_off
- id: '1568486841268'
  alias: Back up to Dropbox
  trigger:
  - at: 00:00:00
    platform: time
  condition: []
  action:
  - service: hassio.snapshot_full
  - data:
      addon: 7be23ff5_dropbox_sync
      input:
        command: upload
    service: hassio.addon_stdin
