default_config:
tts: !include tts.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
wake_on_lan:
device_tracker: !include device_trackers.yaml
light: !include lights.yaml
lovelace: !include lovelace.yaml
zone: !include zones.yaml
speedtestdotnet:
sensor:
  - !include cups.yaml
  - !include system_monitor.yaml
webostv: !include webostv.yaml
