default_config:
tts: !include tts.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
wake_on_lan:
media_player: !include media_players.yaml
device_tracker: !include device_trackers.yaml
light: !include lights.yaml
lovelace: !include lovelace.yaml
zone: !include zones.yaml
sensor:
  - platform: cups
    is_cups_server: false
    host: !secret printer_host
    printers:
      - ipp/print
speedtestdotnet:
