- platform: group
  name: Comodino sinistro
  entities:
    - light.comodino_sinistro_1
    - light.comodino_sinistro_2
- platform: group
  name: Comodino destro
  entities:
    - light.comodino_destro_1
    - light.comodino_destro_2
- platform: group
  name: Ingresso camera da letto
  entities:
    - light.ingresso_camera_da_letto_1
    - light.ingresso_camera_da_letto_2
    - light.ingresso_camera_da_letto_3
    - light.ingresso_camera_da_letto_4
