title: Casa
resources:
  - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
    type: js
  - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
    type: module
views:
  - !include ui-lovelace/people.yaml
  - !include ui-lovelace/climate.yaml
  - !include ui-lovelace/lights.yaml
  - !include ui-lovelace/blinds.yaml
  - !include ui-lovelace/entertainment.yaml
  - !include ui-lovelace/system.yaml
  - !include ui-lovelace/scripts.yaml
