title: Casa
views:
  - path: people
    title: Persone
    badges: []
    cards:
      - entities:
          - entity: person.alessandro_desantis
          - entity: device_tracker.ipad_di_alessandro
          - entity: sensor.ipad_di_alessandro_battery_state
          - entity: sensor.ipad_di_alessandro_battery_level
          - entity: device_tracker.iphone_di_alessandro
          - entity: device_tracker.iphonedessandro_homenet_telecomitalia_it
          - entity: device_tracker.iphone_di_alessandro_bt
          - entity: sensor.iphone_di_alessandro_battery_state
          - entity: sensor.iphone_di_alessandro_battery_level
          - entity: device_tracker.mbpdialessandro_homenet_telecomitalia_it
        show_header_toggle: false
        title: Alessandro
        type: entities
      - entities:
          - entity: person.cloe_filippi
          - entity: device_tracker.iphone_di_cloe
          - entity: device_tracker.iphone_di_cloe_wifi
          - entity: sensor.iphone_di_cloe_battery_state
          - entity: sensor.iphone_di_cloe_battery_level
        show_header_toggle: false
        title: Cloe
        type: entities
  - path: day-area
    title: Zona giorno
    badges:
      - sensor.esterno_salone_temperature
    cards:
      - entity: light.lampada
        type: light
      - entity: media_player.lg_webos_smart_tv
        type: media-control
      - entity: media_player.playstation_4
        type: media-control
      - entity: media_player.soggiorno
        type: media-control
      - entity: climate.salone
        type: thermostat
      - entity: light.ingresso
        type: light
      - entity: light.cucina
        type: light
      - entity: light.vetrina
        type: light
  - path: night-area
    title: Zona notte
    badges:
      - sensor.esterno_studio_temperature
    cards:
      - entity: light.ingresso_camera_da_letto
        name: Ingresso
        type: light
      - entity: light.soffitto_camera_da_letto
        type: light
      - entity: light.comodino_sinistro
        type: light
      - entity: light.comodino_destro
        type: light
      - entity: light.soffitto_studio
        type: light
      - entity: light.ingresso_studio
        type: light
      - entity: climate.studio
        type: thermostat
      - entity: light.bagno_ospiti
        type: light
      - entity: light.bagno_padronale
        type: light
      - entity: light.disimpegno
        type: light
