title: Casa

resources:
  - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: /hacsfiles/banner-card/banner-card.js
    type: module
  - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
    type: module
  - url: /hacsfiles/simple-thermostat/simple-thermostat.js
    type: module
  - url: /hacsfiles/lovelace-card-mod/card-mod.js
    type: module
  - url: /hacsfiles/button-card/button-card.js
    type: module
  - url: /hacsfiles/lovelace-fold-entity-row/fold-entity-row.js
    type: module
  - url: /hacsfiles/decluttering-card/decluttering-card.js
    type: module

decluttering_templates: !include_dir_named ui-lovelace/decluttering_templates
button_card_templates: !include_dir_named ui-lovelace/button_card_templates

views:
  - !include ui-lovelace/views/people.yaml
  - !include ui-lovelace/views/day.yaml
  - !include ui-lovelace/views/night.yaml
  - !include ui-lovelace/views/system.yaml
