title: Casa
resources:
  - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
    type: js
  - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: /hacsfiles/banner-card/banner-card.js
    type: module
views:
  - !include ui-lovelace/people.yaml
  - !include ui-lovelace/day.yaml
  - !include ui-lovelace/night.yaml
  - !include ui-lovelace/system.yaml
