- platform: template
  sensors:
    stufa_current_power:
      friendly_name: "Consumo attuale"
      unit_of_measurement: 'W'
      value_template: "{{ state_attr('switch.stufa', 'current_power_w') }}"
      icon_template: fas:bolt
    stufa_today_consumption:
      friendly_name: "Consumo odierno"
      unit_of_measurement: 'kWh'
      value_template: "{{ state_attr('switch.stufa', 'today_energy_kwh') }}"
      icon_template: fas:bolt
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: swap_use_percent
    - type: processor_use
- platform: template
  sensors:
    lavastoviglie_operation_state:
      friendly_name: "Stato lavastoviglie"
      value_template: "{{ state_attr('switch.lavastoviglie', 'operation_state') }}"
    lavastoviglie_running_program:
      friendly_name: "Programma attivo"
      value_template: >
        {% if state_attr('switch.lavastoviglie', 'active_program') == 'intensiv70' %}
          Intensivo 70°C
        {% elif state_attr('switch.lavastoviglie', 'active_program') == 'auto2' %}
          Auto 45-65°C
        {% elif state_attr('switch.lavastoviglie', 'active_program') == 'eco50' %}
          Eco 50°C
        {% elif state_attr('switch.lavastoviglie', 'active_program') == 'night_wash' %}
          Programma notturno 50°C
        {% elif state_attr('switch.lavastoviglie', 'active_program') == 'kurz60' %}
          Breve 60°C
        {% elif state_attr('switch.lavastoviglie', 'active_program') == 'glas40' %}
          Delicato 40°C
        {% elif state_attr('switch.lavastoviglie', 'active_program') == 'quick45' %}
          Lavaggio rapido 45°C
        {% elif state_attr('switch.lavastoviglie', 'active_program') == 'pre_rinse' %}
          Prelavaggio
        {% elif state_attr('switch.lavastoviglie', 'active_program') == 'machine_care' %}
            Cura lavastoviglie
        {% else %}
          {{ state_attr('switch.lavastoviglie', 'active_program') }}
        {% endif %}
    current_theme:
      friendly_name: "Tema attuale"
      value_template: >
        {% if states('sun.sun') == 'above_horizon' %}
          Google Light Theme
        {% else %}
          Google Dark Theme
        {% endif %}
