- platform: template
  sensors:
    stufa_current_power:
      friendly_name: "Consumo attuale"
      unit_of_measurement: 'W'
      value_template: "{{ state_attr('switch.stufa', 'current_power_w') }}"
      icon_template: fas:bolt
    stufa_today_consumption:
      friendly_name: "Consumo odierno"
      unit_of_measurement: 'kWh'
      value_template: "{{ state_attr('switch.stufa', 'today_energy_kwh') }}"
      icon_template: fas:bolt
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: swap_use_percent
    - type: processor_use
